version: '3.8'

services:

  backend:
    image: saud215/fp-challenge-backend:v1
    container_name: fp-challenge-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app/data:/app/app/data
    restart: always

  frontend:
    image: saud215/fp-challenge-frontend:v1
    container_name: fp-challenge-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: always

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    ports:
      - "9090:9090"
    depends_on:
      - backend
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    restart: always