version: "3.9"

networks:
  fusionpact-network:
    driver: bridge

services:
  frontend:
    image: fusion-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - fusionpact-network

  backend:
    image: fusion-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - backend-data:/app/data   # persist the /data folder
    restart: unless-stopped
    networks:
      - fusionpact-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    networks:
      - fusionpact-network
    restart: unless-stopped
    depends_on:
      - backend
  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    networks:
      - fusionpact-network

  grafana: 
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./monitoring/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/dashboards_json:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
    networks:
      - fusionpact-network
    restart: unless-stopped
volumes:
  backend-data:
    driver: local
  prometheus-data:
    driver: local
