# 1. Use a base Python image
FROM python:3.10-slim

# 2. Set working directory inside container
WORKDIR /app

# 3. Copy requirements first (for caching)
COPY requirements.txt ./

# 4. Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# 5. Copying rest of the files
COPY ./app ./app

# 6. Expose port
EXPOSE 8000

# 7. Running the FastAPI app
# We point Uvicorn to the app module inside the app folder
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]